
Importing the dependencies

In [36]:
import pandas as pd
import numpy as np

In [37]:
import difflib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

Data Collection and Pre-Processing

In [38]:
mov = pd.read_csv("movies.csv")

In [39]:
# Number of rows and columns
mov.shape

(4803, 24)

In [40]:
# Wanted to see the column names
list(mov.columns)

['index',
 'budget',
 'genres',
 'homepage',
 'id',
 'keywords',
 'original_language',
 'original_title',
 'overview',
 'popularity',
 'production_companies',
 'production_countries',
 'release_date',
 'revenue',
 'runtime',
 'spoken_languages',
 'status',
 'tagline',
 'title',
 'vote_average',
 'vote_count',
 'cast',
 'crew',
 'director']

In [41]:
mov.head(5)

index     budget                                    genres  \
0      0  237000000  Action Adventure Fantasy Science Fiction   
1      1  300000000                  Adventure Fantasy Action   
2      2  245000000                    Action Adventure Crime   
3      3  250000000               Action Crime Drama Thriller   
4      4  260000000          Action Adventure Science Fiction   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            keywords original_language  \
0  culture clash future space war space colony so...                en   
1  ocean drug abuse exotic island east india trad...                en   
2         spy based on novel secret agent sequel mi6                en   
3  dc comics crime fighter terrorist secret ident...                en   
4  based on novel mars medallion space travel pri...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            overview  popularity  ... runtime  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577  ...   162.0   
1  Captain Barbossa, long believed to be dead, ha...  139.082615  ...   169.0   
2  A cryptic message from Bond’s past sends him o...  107.376788  ...   148.0   
3  Following the death of District Attorney Harve...  112.312950  ...   165.0   
4  John Carter is a war-weary, former military ca...   43.926995  ...   132.0   

                                    spoken_languages    status  \
0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1           [{"iso_639_1": "en", "name": "English"}]  Released   
2  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released   
3           [{"iso_639_1": "en", "name": "English"}]  Released   
4           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   
3                                 The Legend Ends   
4            Lost in our world, found in another.   

                                      title vote_average vote_count  \
0                                    Avatar          7.2      11800   
1  Pirates of the Caribbean: At World's End          6.9       4500   
2                                   Spectre          6.3       4466   
3                     The Dark Knight Rises          7.6       9106   
4                               John Carter          6.1       2124   

                                                cast  \
0  Sam Worthington Zoe Saldana Sigourney Weaver S...   
1  Johnny Depp Orlando Bloom Keira Knightley Stel...   
2  Daniel Craig Christoph Waltz L\u00e9a Seydoux ...   
3  Christian Bale Michael Caine Gary Oldman Anne ...   
4  Taylor Kitsch Lynn Collins Samantha Morton Wil...   

                                                crew           director  
0  [{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...      James Cameron  
1  [{'name': 'Dariusz Wolski', 'gender': 2, 'depa...     Gore Verbinski  
2  [{'name': 'Thomas Newman', 'gender': 2, 'depar...         Sam Mendes  
3  [{'name': 'Hans Zimmer', 'gender': 2, 'departm...  Christopher Nolan  
4  [{'name': 'Andrew Stanton', 'gender': 2, 'depa...     Andrew Stanton  

[5 rows x 24 columns]

In [42]:
# Selecting relevant features : Feature Selection

features = ['genres', 'keywords', 'tagline', 'overview', 'cast', 'director']
print(features)

['genres', 'keywords', 'tagline', 'overview', 'cast', 'director']


In [43]:
# Checking for count of null values in the features that we have selected

for i in features : 
    print(i,mov[i].isnull().sum())

genres 28
keywords 412
tagline 844
overview 4
cast 43
director 30


In [44]:
# Filling null values 

for i in features : 
    mov[i] = mov[i].fillna('')

In [45]:
# Combining all the features selected

combine = mov["genres"]+' '+mov["keywords"]+' '+mov["tagline"]+' '+mov["overview"]+' '+mov['cast']+' '+mov["director"]

In [46]:
print(combine)

0       Action Adventure Fantasy Science Fiction cultu...
1       Adventure Fantasy Action ocean drug abuse exot...
2       Action Adventure Crime spy based on novel secr...
3       Action Crime Drama Thriller dc comics crime fi...
4       Action Adventure Science Fiction based on nove...
                              ...                        
4798    Action Crime Thriller united states\u2013mexic...
4799    Comedy Romance  A newlywed couple's honeymoon ...
4800    Comedy Drama Romance TV Movie date love at fir...
4801      A New Yorker in Shanghai When ambitious New ...
4802    Documentary obsession camcorder crush dream gi...
Length: 4803, dtype: object


In [47]:
# Converting data to vectors

vectors = TfidfVectorizer()

In [51]:
# Store all the data in numerical values
veccombine = vectors.fit_transform(combine)

In [52]:
print(veccombine)

  (0, 4288)	0.13213124585063998
  (0, 14180)	0.08418056281586365
  (0, 23134)	0.14987864628095252
  (0, 17784)	0.12285843797047788
  (0, 15569)	0.17136669159262102
  (0, 25868)	0.11590870590502834
  (0, 29614)	0.15064979633862854
  (0, 24802)	0.15892578492394402
  (0, 23578)	0.16802034155542867
  (0, 30543)	0.15064979633862854
  (0, 30145)	0.18243919685121027
  (0, 23619)	0.11047375838269541
  (0, 5245)	0.16506865163441017
  (0, 1014)	0.12285843797047788
  (0, 1243)	0.05270709034262742
  (0, 21523)	0.16650106431669984
  (0, 1281)	0.0319519027005067
  (0, 19650)	0.16120557402371172
  (0, 10368)	0.138482776543016
  (0, 2974)	0.09974129089792808
  (0, 27515)	0.1456922041909068
  (0, 2685)	0.09805341831299118
  (0, 4129)	0.06195738171764886
  (0, 18025)	0.1093940665047336
  (0, 28597)	0.15490753406550084
  :	:
  (4802, 27153)	0.05940079357098276
  (4802, 19243)	0.061349419053434766
  (4802, 11941)	0.07829183421073846
  (4802, 29680)	0.07735547381237222
  (4802, 9346)	0.07104321122746965
  

Cosine similarity : Similarity scores

In [53]:
similarity = cosine_similarity(veccombine)

In [54]:
print(similarity)

[[1.         0.05083168 0.0332947  ... 0.02749812 0.0304889  0.0072518 ]
 [0.05083168 1.         0.04356836 ... 0.05077045 0.03100979 0.01521198]
 [0.0332947  0.04356836 1.         ... 0.02646984 0.04751623 0.01372603]
 ...
 [0.02749812 0.05077045 0.02646984 ... 1.         0.03481447 0.03546821]
 [0.0304889  0.03100979 0.04751623 ... 0.03481447 1.         0.03098945]
 [0.0072518  0.01521198 0.01372603 ... 0.03546821 0.03098945 1.        ]]


In [55]:
# Take one movie and compare it with other movies --> gives us similarity score
similarity.shape

(4803, 4803)

In [56]:
# Getting the movie name

movie_name = input("Enter your favourite movie name : ")

Enter your favourite movie name :iron man


In [58]:
# Creating a list with all the movies given in the dataset

list_of_movies = mov['title'].tolist()
print(len(list_of_movies))

4803


In [60]:
# Finding close match for movie name given by the user 

close_match = difflib.get_close_matches(movie_name, list_of_movies)
print(close_match)

['Iron Man', 'Iron Man 3', 'Iron Man 2']


In [62]:
match = close_match[0]
print(match)

Iron Man


In [63]:
# Finding the index of movie

index_of_matched = mov [mov.title == match] ['index'].values[0]
print(index_of_matched)

68


In [65]:
# Getting alist of similar movies
# (0, 0.050174693392667453) --> means that first value is the index, second value is the similarity score of movie compared to "match"

sim_score = list(enumerate(similarity[index_of_matched]))
print(sim_score)

[(0, 0.050174693392667453), (1, 0.03650601760111055), (2, 0.011028940457748972), (3, 0.006566052540268534), (4, 0.026260064582796727), (5, 0.014352343583526096), (6, 0.032839932646772305), (7, 0.19343464286690049), (8, 0.010447641591762171), (9, 0.03661745849142617), (10, 0.03856206332307925), (11, 0.013140335946520334), (12, 0.010480204139154865), (13, 0.010519252119405034), (14, 0.05824054285547451), (15, 0.028506070177881645), (16, 0.13208839109747222), (17, 0.01578360213400237), (18, 0.02078306728232427), (19, 0.042486448120754944), (20, 0.036752005155219786), (21, 0.024462379417016164), (22, 0.009211246725242383), (23, 0.017688499354673565), (24, 0.017920651785080486), (25, 0.003516675934857519), (26, 0.11563787911286948), (27, 0.03304503555209013), (28, 0.03726807159069121), (29, 0.00955791287735387), (30, 0.0796908302150445), (31, 0.29052114405111434), (32, 0.025752500442139028), (33, 0.07770036840942475), (34, 0.005794060102999554), (35, 0.020964205751412706), (36, 0.0253040228

In [66]:
len(sim_score)

4803

In [68]:
# Sorting the movies based on similarity scores(desc order)
# lambda is used : x --> sim_score, x[1] -->scores of movie

sorted_sim_movie_score = sorted(sim_score, key = lambda x:x[1], reverse = True)
print(sorted_sim_movie_score)

[(68, 1.0000000000000002), (79, 0.32928784708836273), (31, 0.29052114405111434), (7, 0.19343464286690049), (16, 0.13208839109747222), (511, 0.11735356375367764), (4401, 0.11644899793001537), (26, 0.11563787911286948), (64, 0.11260372706734421), (182, 0.10817936918053872), (3623, 0.1042757991040167), (94, 0.10008582067970911), (46, 0.08808497545952933), (4033, 0.08653671400103878), (783, 0.08640309672854925), (174, 0.08596763747178217), (618, 0.0842237295387469), (85, 0.08317925570431418), (3133, 0.08003408207059731), (101, 0.07997032837045652), (1740, 0.07985500618953217), (30, 0.0796908302150445), (3466, 0.07863852678986306), (33, 0.07770036840942475), (203, 0.07717739012595404), (1177, 0.07676994814946043), (420, 0.07660248386797325), (131, 0.07526258364935166), (1406, 0.07520922477471761), (318, 0.07470160419701297), (788, 0.07388756055635985), (2229, 0.07375196657625921), (122, 0.07319454323849187), (1135, 0.07304073502421526), (2235, 0.0724818728915707), (138, 0.07246371735320549)

In [75]:
# print the names of similar to the match based on index

print('Movie Suggestion for you : \n')
i = 1

for movie in sorted_sim_movie_score :
    indexx = movie[0]
    
    title_from_index = mov[mov.index == indexx]['title'].values[0]
    
    if (i < 21) :
        print(i, ".", title_from_index)
        i += 1

Movie Suggestion for you : 

1 . Iron Man
2 . Iron Man 2
3 . Iron Man 3
4 . Avengers: Age of Ultron
5 . The Avengers
6 . X-Men
7 . The Helix... Loaded
8 . Captain America: Civil War
9 . X-Men: Apocalypse
10 . Ant-Man
11 . Made
12 . Guardians of the Galaxy
13 . X-Men: Days of Future Past
14 . Super
15 . Mortdecai
16 . The Incredible Hulk
17 . Mystery Men
18 . Captain America: The Winter Soldier
19 . The Devil's Tomb
20 . X-Men: First Class
